#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Railway staging + R2 for W Chats (ticket 18, ADR 0005).
# The four service configs are checked in as apps/api/railway.*.toml; this
# wizard is the human half: create the services, set each service's fields,
# wire Redis and R2, set the variables, and observe /health on the public URL.
#
# CONFIG-AS-CODE IS CLOSED TO NEW SERVICES (#139). Railway's own panel, read on
# the staging dashboard 2026-08-31: "Config as Code is deprecated. Prefer
# Infrastructure as Code. Existing config files keep working until 2026-12-01.
# Starting 2026-08-28, services that have never used Config as Code cannot opt
# in." Every staging service is newer than that date, so pointing a service at
# its toml is the path that MIGHT work, and typing the toml's fields into the
# UI is the path that always does. Both are offered per service below.
#
# The CLI's migrate path does not replace either, verified 2026-09-05 with
# `railway config migrate` on railway 5.47.1. It discovers only files literally
# named railway.toml or railway.json ("No railway.json or railway.toml found in
# this repository" against this directory's four), and on a file it does find it
# emits `builder`, `dockerfilePath`, `preDeployCommand` and `watchPatterns` as
# COMMENTS in .railway/railway.ts rather than as fields. Migrating today would
# silently drop the pre-deploy migrations.

# Interactive only: every checkpoint waits on a human answer, and EOF would
# spin the re-prompt loops forever.
[[ -t 0 ]] || { echo "this wizard needs a terminal (stdin is not a tty)"; exit 1; }

# apps/api, wherever this script was invoked from. The per-service field lists
# below are read out of the tomls that live there, so the wizard cannot drift
# from the files that are the record.
API_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# toml_value FILE KEY prints the value of a top-level `KEY = ...` line, quotes
# and brackets intact so what is printed is the literal the file carries.
# The four service files are flat (one [build] table, one [deploy] table, no
# nesting), so a line match is the whole parser this needs.
toml_value() {
  local line
  line=$(grep -E "^${2} = " "$API_DIR/${1}" | head -n1) || return 1
  printf '%s' "${line#* = }"
}

# service_fields FILE prints every field the Railway UI needs for one service,
# read out of that service's toml. Fields absent from a file are skipped, so
# beat's single replica and the api's health check and pre-deploy command each
# appear on exactly the service that carries them.
service_fields() {
  local file="$1" value
  note "  Settings > Source > Root Directory        apps/api"
  note "  Settings > Build > Builder                $(toml_value "$file" builder)"
  note "  Settings > Build > Dockerfile Path        $(toml_value "$file" dockerfilePath)"
  note "  Settings > Build > Watch Paths            $(toml_value "$file" watchPatterns)"
  if value="$(toml_value "$file" preDeployCommand)"; then
    note "  Settings > Deploy > Pre-Deploy Command    $value"
  fi
  note "  Settings > Deploy > Custom Start Command  $(toml_value "$file" startCommand)"
  if value="$(toml_value "$file" healthcheckPath)"; then
    note "  Settings > Deploy > Healthcheck Path      $value"
  fi
  if value="$(toml_value "$file" healthcheckTimeout)"; then
    note "  Settings > Deploy > Healthcheck Timeout   $value"
  fi
  if value="$(toml_value "$file" numReplicas)"; then
    note "  Settings > Deploy > Replicas              $value"
  fi
  note "  Settings > Deploy > Restart Policy        $(toml_value "$file" restartPolicyType)"
  note "  Settings > Deploy > Max Retries           $(toml_value "$file" restartPolicyMaxRetries)"
}

# service_config STAGE_FILE SERVICE_NAME walks the one decision every service
# stage has to make: use the checked-in toml if this service is allowed to, and
# type its fields in by hand if it is not.
service_config() {
  local file="$1" service="$2"
  step "Settings > Source > Root Directory = apps/api"
  say "Open Settings and look for a Config-as-code section (#139: Railway"
  say "closed it to services created after 2026-08-28)."
  if confirm "Does $service offer a Config-as-code file path you can set?"; then
    step "Settings > Config-as-code > file path = $file"
    note "If the deploy IGNORES the toml (wrong start command in the deploy log),"
    note "Railway resolved the path from the repo root: set it to"
    note "apps/api/$file instead, and the same for the other three."
  else
    say "Then $file is documentation, not applied config. Type these into"
    say "$service by hand; every value is read out of that file:"
    service_fields "$file"
    SKIPPED+=("$service: fields typed by hand from $file, so a change to that file does NOT reach Railway")
  fi
  until confirm "$service configured?"; do say "Finish the step above, then answer y."; done
}

# Captured values persist here, never in .env: the local .env is the dev
# seam (MinIO) and these are Railway-side facts.
ENV_FILE="${ENV_FILE:-.railway-staging.env}"

TOTAL_STAGES=10

banner "W Chats on Railway: staging + R2"

# ──────────────────────────────────────────────────────────────────────────
stage "Railway project from the GitHub repo"
say "One project holds all four services and the Redis plugin."
open_url "https://railway.com/new"
step "Sign in, choose 'Deploy from GitHub repo', authorize, pick the wchats repo"
step "If it starts a deploy immediately, let it fail; the next stages fix the source"
note "Staging and production are two environments in this one project (decision #14.5)."
until confirm "Project exists and the repo is connected?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "The \$20 hard limit, before anything can bill"
say "Railway's user-set hard cap takes workloads offline when hit; that cap is"
say "why Railway won over Fly and Render (decision #14.1)."
open_url "https://railway.com/workspace/usage"
step "Workspace Settings > Usage > set a HARD limit of \$20"
if ! confirm "Hard limit saved at \$20?"; then
  warn "Hard limits are plan-gated on some Railway tiers. Do not deploy real"
  warn "credentials until a spend cap exists somewhere."
  SKIPPED+=("the \$20 hard limit: set it before real credentials go in")
fi

# ──────────────────────────────────────────────────────────────────────────
stage "api service"
say "Each service carries the same set of fields. They come from that service's"
say "checked-in toml, either because Railway reads the file or because you type"
say "them in from it."
step "On the service created from the repo (or + New > GitHub Repo):"
note "The first green build's log opens with 'Using Detected Dockerfile'."
note "A 9-second 'Railpack could not determine how to build' means Root Directory is unset."
service_config railway.api.toml "api service"
note "The pre-deploy command is the release step that brings the control DB and"
note "every tenant DB to head. Without it a deploy ships code against the schema"
note "it had before, which is how staging sat at 0020 under 0022 code."

# ──────────────────────────────────────────────────────────────────────────
stage "worker-runtime service"
step "+ New > GitHub Repo > the same wchats repo"
note "The cheap worker: agent turns and evals, no docling, no public networking."
service_config railway.worker-runtime.toml "worker-runtime"

# ──────────────────────────────────────────────────────────────────────────
stage "beat service"
step "+ New > GitHub Repo > the same repo"
note "One replica, never scaled. Schedules arm per agent at deploy: every beat"
note "fans out to is_deployed agents only, so an empty staging idles cheaply."
service_config railway.beat.toml "beat"

# ──────────────────────────────────────────────────────────────────────────
stage "worker-pipeline service (optional today)"
say "The 3 GB docling image. On the trial budget, add it for the hour an upload"
say "is being tested and remove it afterwards; it idles at far more RAM than"
say "the other three (the file's own header says the same)."
if confirm "Add the pipeline worker now?"; then
  step "+ New > GitHub Repo > the same repo"
  service_config railway.worker-pipeline.toml "worker-pipeline"
  step "Variables tab, add exactly these two:"
  note "  LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu"
  note "  HF_HUB_DISABLE_XET_ENDPOINT=1"
  until confirm "pipeline worker has both variables?"; do say "Finish the step above, then answer y."; done
else
  note "Skipped. Ingestion stays down until it exists; everything else serves."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Redis plugin, wired to all services"
step "+ New > Database > Redis"
step "On EACH service's Variables tab add a reference:"
note '  REDIS_URL=${{Redis.REDIS_URL}}'
say "Broker and SSE pub/sub both ride this one URL."
until confirm "Every service has the REDIS_URL reference?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "R2 bucket and S3 credentials"
say "Object storage is R2 through the existing S3 seam. Production accepts one"
say "host, the one you name below, and refuses every other endpoint. The"
say "*.r2.cloudflarestorage.com suffix alone is not the bound: every R2 tenant"
say "on earth carries it, so the host has to be yours by name (#133)."
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "R2 > Create bucket, name: wchats-uploads (any region)"
step "R2 > Manage R2 API Tokens > Create API Token:"
step "  permission 'Object Read & Write', scoped to that bucket"
step "Copy three things: Access Key ID, Secret Access Key, and the S3 endpoint"
note "  (https://<account-id>.r2.cloudflarestorage.com)"
until confirm "Bucket and token created, three values copied somewhere safe?"; do say "Finish the step above, then answer y."; done
# The key written here is the Settings field name, not a wizard-local alias:
# every later line reads this value back to build the variable the operator
# pastes into Railway, and an alias makes the .env and the platform disagree
# about which name carries the host.
#
# The refusal loops rather than warning and writing anyway. A rejected value
# written to .env is offered back as the default on the next run, so the wizard
# would keep handing the operator the paste the API refuses to boot on. The
# accepted shapes are exactly the ones config.py accepts: no scheme, path or
# credentials, no port, no whitespace inside.
S3_EXPECTED_ENDPOINT_HOST=""
while :; do
  ask S3_EXPECTED_ENDPOINT_HOST \
    "Paste the endpoint's HOST only, no https:// and no path (Enter alone skips):"
  S3_EXPECTED_ENDPOINT_HOST="$(printf '%s' "$S3_EXPECTED_ENDPOINT_HOST" | tr 'A-Z' 'a-z')"
  ENDPOINT_HOST_REASON=""
  case "$S3_EXPECTED_ENDPOINT_HOST" in
    "")            break ;;
    *://*|*/*|*@*) ENDPOINT_HOST_REASON="That is a URL, not a host." ;;
    *:*)           ENDPOINT_HOST_REASON="That carries a port. The API compares it against a parsed hostname, which never has one." ;;
    *[[:space:]]*) ENDPOINT_HOST_REASON="That has whitespace inside the host." ;;
  esac
  if [[ -z "$ENDPOINT_HOST_REASON" ]]; then break; fi
  warn "$ENDPOINT_HOST_REASON"
  warn "S3_EXPECTED_ENDPOINT_HOST takes the host on its own and the API refuses"
  warn "to boot on anything else. Paste only <account-id>.r2.cloudflarestorage.com,"
  warn "or press Enter alone to skip this and set it by hand later."
done
if [[ -n "$S3_EXPECTED_ENDPOINT_HOST" ]]; then
  write_env S3_EXPECTED_ENDPOINT_HOST "$S3_EXPECTED_ENDPOINT_HOST"
else
  SKIPPED+=("S3_EXPECTED_ENDPOINT_HOST: the bare host; production refuses to boot without it")
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Shared variables on Railway"
say "Project > Variables (shared across services). The nine no-default"
say "settings (the set tests/unit/test_env_example_covers_required_settings.py"
say "derives, checked against it 2026-08-31):"
note "  NEON_API_KEY            NEON_ENCRYPTION_KEY   PLATFORM_CREDENTIAL_KEY"
note "  CONTROL_DB_URL          CONTROL_DB_SYNC_URL   ADMIN_KEY"
note "  VOYAGE_API_KEY          JWT_SECRET            CLERK_WEBHOOK_SIGNING_SECRET"
say "Plus, for this stack:"
note "  OPENAI_API_KEY          (every routed purpose serves gpt-5.6-luna)"
note "  ANTHROPIC_API_KEY       (defaults empty; #88's residual clients read it)"
note "  EMBEDDING_PROVIDER=voyage"
note "  ENVIRONMENT=production  (type EXACTLY that word: it arms the storage"
note "                           allowlist, hides /docs, refuses loopback"
note "                           snippets and redacts token errors; an unknown"
note "                           word refuses to boot)"
note "  S3_ENDPOINT_URL=https://${S3_EXPECTED_ENDPOINT_HOST:-<account-id>.r2.cloudflarestorage.com}"
note "  S3_EXPECTED_ENDPOINT_HOST=${S3_EXPECTED_ENDPOINT_HOST:-<account-id>.r2.cloudflarestorage.com}"
note "                          (the host on its own, no https:// and no path;"
note "                           production refuses to boot without it, and"
note "                           refuses any other host at upload time)"
note "  S3_UPLOADS_BUCKET=wchats-uploads"
note "  S3_ACCESS_KEY_ID=<the R2 token's Access Key ID>"
note "  S3_SECRET_ACCESS_KEY=<the R2 token's Secret Access Key>"
note "                          named for the protocol, not the vendor, because"
note "                           the store is R2. storage_service passes these"
note "                           two to boto3 explicitly and reads no default"
note "                           credential chain, so the vendor-prefixed"
note "                           spellings reach nothing and the first upload"
note "                           answers 503 naming the two above."
warn "CONTROL_DB_URL / CONTROL_DB_SYNC_URL: create a SEPARATE Neon control"
warn "project for staging. The repo .env's DSNs are LIVE PRODUCTION; pasted"
warn "here, the staging beat spends nightly eval money on production agents."
until confirm "All variables saved?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "Deploy and observe /health"
step "api service > Settings > Networking > Generate Domain; copy the URL"
step "Add PUBLIC_API_BASE=<that URL> to the shared variables (the embed"
step "snippet route refuses the localhost default in production)"
step "Deployments > redeploy anything that did not pick the variables up"
step "Open worker-runtime and beat Deploy Logs; each must show celery 'ready'"
ask STAGING_API_BASE "Paste the api service's public URL (https://...):"
write_env STAGING_API_BASE "${STAGING_API_BASE%/}"
say "Checking ${STAGING_API_BASE%/}/health ..."
if command -v curl >/dev/null 2>&1 && curl -fsS -m 15 "${STAGING_API_BASE%/}/health" >/dev/null 2>&1; then
  say "✓ /health answers: the api half of criterion (a). The worker-and-beat"
  say "  half is the two 'ready' log lines from the step above."
  note "If .dev/debug/railway-first-build.md exists in this checkout, delete it."
else
  warn "/health did not answer. Read the api service's build and deploy logs;"
  warn "the first line of a good build is 'Using Detected Dockerfile'."
  SKIPPED+=("staging /health check: rerun this wizard once the deploy is green")
fi

finish
