#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Railway staging + R2 for W Chats (ticket 18, ADR 0005).
# The four service configs are checked in as apps/api/railway.*.toml; this
# wizard is the human half: create the services, point each at its file, wire
# Redis and R2, set the variables, and observe /health on the public URL.

TOTAL_STAGES=10

banner "W Chats on Railway: staging + R2"

# ──────────────────────────────────────────────────────────────────────────
stage "Railway project from the GitHub repo"
say "One project holds all four services and the Redis plugin."
open_url "https://railway.com/new"
step "Sign in, choose 'Deploy from GitHub repo', authorize, pick the wchats repo"
step "If it starts a deploy immediately, let it fail; the next stages fix the source"
note "Staging and production are two environments in this one project (decision #14.5)."
until confirm "Project exists and the repo is connected?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "The \$20 hard limit, before anything can bill"
say "Railway's user-set hard cap takes workloads offline when hit; that cap is"
say "why Railway won over Fly and Render (decision #14.1)."
open_url "https://railway.com/workspace/usage"
step "Workspace Settings > Usage > set a HARD limit of \$20"
until confirm "Hard limit saved at \$20?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "api service"
say "Each service reads its own checked-in config file; two fields live in the"
say "UI per service and cannot be config-as-code."
step "On the service created from the repo (or + New > GitHub Repo):"
step "Settings > Source > Root Directory = apps/api"
step "Settings > Config-as-code > file path = railway.api.toml"
note "The first green build's log opens with 'Using Detected Dockerfile'."
note "A 9-second 'Railpack could not determine how to build' means Root Directory is unset."
until confirm "api service points at apps/api and railway.api.toml?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "worker-runtime service"
step "+ New > GitHub Repo > the same wchats repo"
step "Settings > Source > Root Directory = apps/api"
step "Settings > Config-as-code > file path = railway.worker-runtime.toml"
note "The cheap worker: agent turns and evals, no docling, no public networking."
until confirm "worker-runtime configured?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "beat service"
step "+ New > GitHub Repo > the same repo"
step "Settings > Source > Root Directory = apps/api"
step "Settings > Config-as-code > file path = railway.beat.toml"
note "One replica, never scaled. Schedules arm per agent at deploy: every beat"
note "fans out to is_deployed agents only, so an empty staging idles cheaply."
until confirm "beat configured?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "worker-pipeline service (optional today)"
say "The 3 GB docling image. On the trial budget, add it for the hour an upload"
say "is being tested and remove it afterwards; it idles at far more RAM than"
say "the other three (the file's own header says the same)."
if confirm "Add the pipeline worker now?"; then
  step "+ New > GitHub Repo > the same repo"
  step "Settings > Source > Root Directory = apps/api"
  step "Settings > Config-as-code > file path = railway.worker-pipeline.toml"
  step "Variables tab, add exactly these two:"
  note "  LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu"
  note "  HF_HUB_DISABLE_XET_ENDPOINT=1"
  until confirm "pipeline worker configured with both variables?"; do say "Finish the step above, then answer y."; done
else
  note "Skipped. Ingestion stays down until it exists; everything else serves."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Redis plugin, wired to all services"
step "+ New > Database > Redis"
step "On EACH service's Variables tab add a reference:"
note '  REDIS_URL=${{Redis.REDIS_URL}}'
say "Broker and SSE pub/sub both ride this one URL."
until confirm "Every service has the REDIS_URL reference?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "R2 bucket and S3 credentials"
say "Object storage is R2 through the existing S3 seam; production accepts"
say "exactly *.r2.cloudflarestorage.com and *.backblazeb2.com and refuses"
say "every other endpoint."
open_url "https://dash.cloudflare.com/?to=/:account/r2"
step "R2 > Create bucket, name: wchats-uploads (any region)"
step "R2 > Manage R2 API Tokens > Create API Token:"
step "  permission 'Object Read & Write', scoped to that bucket"
step "Copy three things: Access Key ID, Secret Access Key, and the S3 endpoint"
note "  (https://<account-id>.r2.cloudflarestorage.com)"
until confirm "Bucket and token created, three values copied somewhere safe?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "Shared variables on Railway"
say "Project > Variables (shared across services). The required set is derived"
say "by tests/unit/test_env_example_covers_required_settings.py; today it is:"
note "  NEON_API_KEY            NEON_ENCRYPTION_KEY   PLATFORM_CREDENTIAL_KEY"
note "  CONTROL_DB_URL          CONTROL_DB_SYNC_URL   ADMIN_KEY"
note "  ANTHROPIC_API_KEY       VOYAGE_API_KEY        JWT_SECRET"
note "  CLERK_WEBHOOK_SIGNING_SECRET"
say "Plus, for this stack:"
note "  OPENAI_API_KEY          (every routed purpose serves gpt-5.6-luna)"
note "  EMBEDDING_PROVIDER=voyage"
note "  ENVIRONMENT=production  (staging is production-shaped: the storage"
note "                           allowlist and the snippet guard key off it)"
note "  S3_ENDPOINT_URL=<the R2 endpoint>    S3_UPLOADS_BUCKET=wchats-uploads"
note "  AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY = the R2 token pair"
warn "CONTROL_DB_URL / CONTROL_DB_SYNC_URL: the Neon control project's DSNs."
until confirm "All variables saved?"; do say "Finish the step above, then answer y."; done

# ──────────────────────────────────────────────────────────────────────────
stage "Deploy and observe /health"
step "api service > Settings > Networking > Generate Domain; copy the URL"
step "Add PUBLIC_API_BASE=<that URL> to the shared variables (the embed"
step "snippet route refuses the localhost default in production)"
step "Deployments > redeploy anything that did not pick the variables up"
ask STAGING_API_BASE "Paste the api service's public URL (https://...):"
say "Checking ${STAGING_API_BASE%/}/health ..."
if command -v curl >/dev/null 2>&1 && curl -fsS -m 15 "${STAGING_API_BASE%/}/health" >/dev/null 2>&1; then
  say "✓ /health answers. Staging serves; acceptance criterion (a) is observed."
  note "Delete .dev/debug/railway-first-build.md; its build succeeded."
else
  warn "/health did not answer. Read the api service's build and deploy logs;"
  warn "the first line of a good build is 'Using Detected Dockerfile'."
  SKIPPED+=("staging /health check: rerun this wizard once the deploy is green")
fi

finish
